CREATE TABLE IF NOT EXISTS team(
   name  VARCHAR(27) NOT NULL PRIMARY KEY
  ,home  VARCHAR(42) NOT NULL
  ,coach VARCHAR(17) NOT NULL
  ,city  VARCHAR(20) NOT NULL
  ,label VARCHAR(4) NOT NULL
);


INSERT INTO team(name,home,coach,city,label) VALUES ('Mumbai Indians','Wankhede Stadium, Mumbai','Mahela Jaywardene','Mumbai, Maharashtra','MI');
INSERT INTO team(name,home,coach,city,label) VALUES ('Delhi Capitals','Feroz Shah Kotla Ground','Ricky Ponting','Delhi, NCR','DC');
INSERT INTO team(name,home,coach,city,label) VALUES ('Kings XI Punjab','IS Bindra Stadium','Anil Kumble','Mohali, Punjab','KXIP');
INSERT INTO team(name,home,coach,city,label) VALUES ('Kolkata Knight Riders','Eden Gardens','Brendon McCullum','Kolkata, West Bengal','KKR');
INSERT INTO team(name,home,coach,city,label) VALUES ('Rajasthan Royals','Sawai Mansingh Stadium','Andrew McDonald','Jaipur, Rajasthan','RR');
INSERT INTO team(name,home,coach,city,label) VALUES ('Royal Challengers Bangalore','M. Chinnaswamy Stadium','Simon Katich','Bengaluru, Karnataka','RCB');
INSERT INTO team(name,home,coach,city,label) VALUES ('Sunrisers Hyderabad','Rajiv Gandhi International Cricket Stadium','Trevor Bayliss','Hyderabad, Telengana','SRH');
INSERT INTO team(name,home,coach,city,label) VALUES ('Chennai Super Kings','M.A. Chidambaram Stadium, Chennai','Stephen Fleming','Chennai, Tamil Nadu','CSK');





CREATE TABLE IF NOT EXISTS player(
   name  VARCHAR(24) NOT NULL PRIMARY KEY
  ,price NUMERIC(11,1) NOT NULL
  ,role  VARCHAR(13) NOT NULL
  ,label VARCHAR(4) NOT NULL references team(label)
);
INSERT INTO player(name,price,role,label) VALUES ('Rohit Sharma (R)',150000000.0,'Batsman','MI');
INSERT INTO player(name,price,role,label) VALUES ('Anmolpreet Singh (R)',8000000.0,'Batsman','MI');
INSERT INTO player(name,price,role,label) VALUES ('Ankul Roy (R)',2000000.0,'Batsman','MI');
INSERT INTO player(name,price,role,label) VALUES ('Sherfane Rutherford (R)',20000000.0,'Batsman','MI');
INSERT INTO player(name,price,role,label) VALUES ('Suryakumar Yadav (R)',32000000.0,'Batsman','MI');
INSERT INTO player(name,price,role,label) VALUES ('Chris Lynn',20000000.0,'Batsman','MI');
INSERT INTO player(name,price,role,label) VALUES ('Saurabh Tiwary',5000000.0,'Batsman','MI');
INSERT INTO player(name,price,role,label) VALUES ('Aditya Tare (R)',2000000.0,'Wicket Keeper','MI');
INSERT INTO player(name,price,role,label) VALUES ('Ishan Kishan (R)',62000000.0,'Wicket Keeper','MI');
INSERT INTO player(name,price,role,label) VALUES ('Quinton de Kock (R)',28000000.0,'Wicket Keeper','MI');
INSERT INTO player(name,price,role,label) VALUES ('Hardik Pandya (R)',110000000.0,'All-Rounder','MI');
INSERT INTO player(name,price,role,label) VALUES ('Kieron Pollard (R)',54000000.0,'All-Rounder','MI');
INSERT INTO player(name,price,role,label) VALUES ('Krunal Pandya (R)',88000000.0,'All-Rounder','MI');
INSERT INTO player(name,price,role,label) VALUES ('Rahul Chahar (R)',19000000.0,'All-Rounder','MI');
INSERT INTO player(name,price,role,label) VALUES ('Digvijay Deshmukh',2000000.0,'All-Rounder','MI');
INSERT INTO player(name,price,role,label) VALUES ('Prince Balwant Rai Singh',2000000.0,'All-Rounder','MI');
INSERT INTO player(name,price,role,label) VALUES ('Dhawal Kulkarni (R)',7500000.0,'Bowler','MI');
INSERT INTO player(name,price,role,label) VALUES ('Jasprit Bumrah (R)',70000000.0,'Bowler','MI');
INSERT INTO player(name,price,role,label) VALUES ('Jayant Yadav (R)',5000000.0,'Bowler','MI');
INSERT INTO player(name,price,role,label) VALUES ('Lasith Malinga (R)',20000000.0,'Bowler','MI');
INSERT INTO player(name,price,role,label) VALUES ('Mitchell McClenaghan (R)',10000000.0,'Bowler','MI');
INSERT INTO player(name,price,role,label) VALUES ('Trent Boult (R)',32000000.0,'Bowler','MI');
INSERT INTO player(name,price,role,label) VALUES ('Nathan Coulter-Nile',80000000.0,'Bowler','MI');
INSERT INTO player(name,price,role,label) VALUES ('Mohsin Khan',2000000.0,'Bowler','MI');
INSERT INTO player(name,price,role,label) VALUES ('Shreyas Iyer (R)',70000000.0,'Batsman','DC');
INSERT INTO player(name,price,role,label) VALUES ('Ajinkya Rahane (R)',52500000.0,'Batsman','DC');
INSERT INTO player(name,price,role,label) VALUES ('Avesh Khan (R)',7000000.0,'Batsman','DC');
INSERT INTO player(name,price,role,label) VALUES ('Keemo Paul (R)',5000000.0,'Batsman','DC');
INSERT INTO player(name,price,role,label) VALUES ('Prithvi Shaw (R)',12000000.0,'Batsman','DC');
INSERT INTO player(name,price,role,label) VALUES ('Shikhar Dhawan (R)',52000000.0,'Batsman','DC');
INSERT INTO player(name,price,role,label) VALUES ('Shimron Heymyer',77500000.0,'Batsman','DC');
INSERT INTO player(name,price,role,label) VALUES ('Jason Roy',15000000.0,'Batsman','DC');
INSERT INTO player(name,price,role,label) VALUES ('Rishabh Pant (R)',150000000.0,'Wicket Keeper','DC');
INSERT INTO player(name,price,role,label) VALUES ('Alex Carey',24000000.0,'Wicket Keeper','DC');
INSERT INTO player(name,price,role,label) VALUES ('Marcus Stoinis',48000000.0,'All-Rounder','DC');
INSERT INTO player(name,price,role,label) VALUES ('Lalit Yadav',2000000.0,'All-Rounder','DC');
INSERT INTO player(name,price,role,label) VALUES ('Chris Woakes',15000000.0,'All-Rounder','DC');
INSERT INTO player(name,price,role,label) VALUES ('Ravichandran Ashwin (R)',76000000.0,'Bowler','DC');
INSERT INTO player(name,price,role,label) VALUES ('Sandeep Lamichhane (R)',2000000.0,'Bowler','DC');
INSERT INTO player(name,price,role,label) VALUES ('Axax Patel (R)',50000000.0,'Bowler','DC');
INSERT INTO player(name,price,role,label) VALUES ('Harshal Patel (R)',2000000.0,'Bowler','DC');
INSERT INTO player(name,price,role,label) VALUES ('Ishant Sharma (R)',11000000.0,'Bowler','DC');
INSERT INTO player(name,price,role,label) VALUES ('Kagiso Rabada (R)',42000000.0,'Bowler','DC');
INSERT INTO player(name,price,role,label) VALUES ('Mohit Sharma',5000000.0,'Bowler','DC');
INSERT INTO player(name,price,role,label) VALUES ('Tushar Deshpande',2000000.0,'Bowler','DC');
INSERT INTO player(name,price,role,label) VALUES ('Amit Mishra (R)',40000000.0,'Bowler','DC');
INSERT INTO player(name,price,role,label) VALUES ('Karun Nair (R)',56000000.0,'Batsman','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Arshdeep Singh (R)',2000000.0,'Batsman','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Chris Gayle (R)',20000000.0,'Batsman','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Darshan Nalkande (R)',3000000.0,'Batsman','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Gowtham Krishnappa (R)',62000000.0,'Batsman','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Hardus Viljoen (R)',7500000.0,'Batsman','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Harpreet Brar (R)',2000000.0,'Batsman','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Mayank Agarwal (R)',10000000.0,'Batsman','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Nicholas Pooran (R)',42000000.0,'Batsman','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Sarfaraz Khan (R)',2500000.0,'Batsman','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Prabhsimran Singh',5500000.0,'Wicket Keeper','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('KL Rahul (R)',110000000.0,'Wicket Keeper','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Mandeep Singh (R)',14000000.0,'All-Rounder','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Glenn Maxwell',107500000.0,'All-Rounder','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Chris Jordan',30000000.0,'All-Rounder','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Deepak Hooda',5000000.0,'All-Rounder','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('James Neesham',5000000.0,'All-Rounder','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Tajinder Dhillon',2000000.0,'All-Rounder','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Ishan Patel',2000000.0,'Bowler','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Jagadeesha Suchith (R)',2000000.0,'Bowler','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Mohammad Shami (R)',48000000.0,'Bowler','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Ravi Bishnoi',20000000.0,'Bowler','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Sheldon Cottrell',85000000.0,'Bowler','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Murugan Ashwin (R)',2000000.0,'Bowler','KXIP');
INSERT INTO player(name,price,role,label) VALUES ('Andre Russell (R)',85000000.0,'Batsman','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Harry Gurney (R)',7500000.0,'Batsman','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Kamlesh Nagarkoti (R)',32000000.0,'Batsman','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Lockie Ferguson (R)',16000000.0,'Batsman','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Nitish Rana (R)',34000000.0,'Batsman','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Prasidh Krishna (R)',2000000.0,'Batsman','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Rinku Singh (R)',8000000.0,'Batsman','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Shubham Gill (R)',18000000.0,'Batsman','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Siddhesh Lad (R)',2000000.0,'Batsman','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Eoin Morgan',52500000.0,'Batsman','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Tom Banton',10000000.0,'Batsman','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Rahul Tripathi',6000000.0,'Batsman','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Dinesh Karthik (R)',74000000.0,'Wicket Keeper','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Nikhil Shankar Naik',2000000.0,'Wicket Keeper','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Sunil Narine (R)',125000000.0,'All-Rounder','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Pat Cummins',155000000.0,'All-Rounder','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Shivam Mavi (R)',30000000.0,'All-Rounder','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Varun Chakaravarthy',40000000.0,'All-Rounder','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Chris Green',2000000.0,'All-Rounder','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Kuldeep Yadav (R)',58000000.0,'Bowler','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Sandeep Warrier (R)',2000000.0,'Bowler','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Pravin Tambe',2000000.0,'Bowler','KKR');
INSERT INTO player(name,price,role,label) VALUES ('M Siddharth',2000000.0,'Bowler','KKR');
INSERT INTO player(name,price,role,label) VALUES ('Riyan Parag (R)',2000000.0,'Batsman','RR');
INSERT INTO player(name,price,role,label) VALUES ('Shashank Singh (R)',3000000.0,'Batsman','RR');
INSERT INTO player(name,price,role,label) VALUES ('Steve Smith (R)',125000000.0,'Batsman','RR');
INSERT INTO player(name,price,role,label) VALUES ('Robin Uthappa',30000000.0,'Batsman','RR');
INSERT INTO player(name,price,role,label) VALUES ('David Miller',7500000.0,'Batsman','RR');
INSERT INTO player(name,price,role,label) VALUES ('Manan Vohra (R)',2000000.0,'Batsman','RR');
INSERT INTO player(name,price,role,label) VALUES ('Jos Butler (R)',44000000.0,'Wicket Keeper','RR');
INSERT INTO player(name,price,role,label) VALUES ('Sanju Samson (R)',80000000.0,'Wicket Keeper','RR');
INSERT INTO player(name,price,role,label) VALUES ('Anuj Rawat',8000000.0,'Wicket Keeper','RR');
INSERT INTO player(name,price,role,label) VALUES ('Ben Stokes (R)',125000000.0,'All-Rounder','RR');
INSERT INTO player(name,price,role,label) VALUES ('Mahipal Lmoror (R)',2000000.0,'All-Rounder','RR');
INSERT INTO player(name,price,role,label) VALUES ('Shreyas Gopal (R)',2000000.0,'All-Rounder','RR');
INSERT INTO player(name,price,role,label) VALUES ('Yashasvi Jaiswal',24000000.0,'All-Rounder','RR');
INSERT INTO player(name,price,role,label) VALUES ('Tom Curran',10000000.0,'All-Rounder','RR');
INSERT INTO player(name,price,role,label) VALUES ('Ankit Rajpoot (R)',30000000.0,'Bowler','RR');
INSERT INTO player(name,price,role,label) VALUES ('Jofra Archer (R)',72000000.0,'Bowler','RR');
INSERT INTO player(name,price,role,label) VALUES ('Mayank Markande (R)',20000000.0,'Bowler','RR');
INSERT INTO player(name,price,role,label) VALUES ('Rahul Tweatia (R)',30000000.0,'Bowler','RR');
INSERT INTO player(name,price,role,label) VALUES ('Varun Aaron (R)',24000000.0,'Bowler','RR');
INSERT INTO player(name,price,role,label) VALUES ('Jaydev Unadkat',30000000.0,'Bowler','RR');
INSERT INTO player(name,price,role,label) VALUES ('Kartik Tyagi',13000000.0,'Bowler','RR');
INSERT INTO player(name,price,role,label) VALUES ('Andrew Tye',10000000.0,'Bowler','RR');
INSERT INTO player(name,price,role,label) VALUES ('Oshane Thomas',5000000.0,'Bowler','RR');
INSERT INTO player(name,price,role,label) VALUES ('Anirudha Ashok Joshi',2000000.0,'All-Rounder','RR');
INSERT INTO player(name,price,role,label) VALUES ('Akash Singh',2000000.0,'Bowler','RR');
INSERT INTO player(name,price,role,label) VALUES ('Virat Kohli (R)',170000000.0,'Batsman','RCB');
INSERT INTO player(name,price,role,label) VALUES ('AB de Villiers (R)',110000000.0,'Batsman','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Devdutt Padikkal (R)',2000000.0,'Batsman','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Gurkeerat Singh (R)',5000000.0,'Batsman','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Aaron Finch',44000000.0,'Batsman','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Shahbaz Ahamad',2000000.0,'Wicket Keeper','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Joshua Philippe',2000000.0,'Wicket Keeper','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Pathiv Patel (R)',17000000.0,'Wicket Keeper','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Pawan Negi (R)',10000000.0,'All-Rounder','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Shivam Dube (R)',50000000.0,'All-Rounder','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Moeen Ali (R)',17000000.0,'All-Rounder','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Isuru Udana',5000000.0,'All-Rounder','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Pavan Deshpande',2000000.0,'All-Rounder','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Christopher Morris',100000000.0,'All-Rounder','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Kane Richardson',40000000.0,'Bowler','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Dale Steyn',20000000.0,'Bowler','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Mohammaed Siraj (R)',26000000.0,'Bowler','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Navdeep Saini (R)',30000000.0,'Bowler','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Umesh Yadav (R)',42000000.0,'Bowler','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Washington Sundar (R)',32000000.0,'Bowler','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Yuzvendra Chahal (R)',60000000.0,'Bowler','RCB');
INSERT INTO player(name,price,role,label) VALUES ('Kane Williamson',30000000.0,'Batsman','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Abhishek Sharma (R)',5500000.0,'Batsman','SRH');
INSERT INTO player(name,price,role,label) VALUES ('David Warner (R)',125000000.0,'Batsman','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Manish Pandey (R)',110000000.0,'Batsman','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Priyam Garg',19000000.0,'Batsman','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Virat Singh',19000000.0,'Batsman','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Jonny Bairstow (R)',22000000.0,'Wicket Keeper','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Shreevats Goswami (R)',10000000.0,'Wicket Keeper','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Wridhhiman Saha (R)',12000000.0,'Wicket Keeper','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Vijay Shankar (R)',32000000.0,'All-Rounder','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Mitchell Marsh',20000000.0,'All-Rounder','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Mohammad Nabi (R)',10000000.0,'All-Rounder','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Fabian Allen',5000000.0,'All-Rounder','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Sandeep Bavanaka',2000000.0,'All-Rounder','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Sanjay Yadav',2000000.0,'All-Rounder','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Abdul Samad',2000000.0,'All-Rounder','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Basil Thampi (R)',9500000.0,'Bowler','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Bhuvneshwar Kumar (R)',85000000.0,'Bowler','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Billy Stanlake (R)',5000000.0,'Bowler','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Rashid Khan (R)',90000000.0,'Bowler','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Sandeep Sharma (R)',30000000.0,'Bowler','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Shahbaz Nadeem (R)',32000000.0,'Bowler','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Siddarth Kaul (R)',38000000.0,'Bowler','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Syed Khaleel Ahmed (R)',30000000.0,'Bowler','SRH');
INSERT INTO player(name,price,role,label) VALUES ('T Natarajan (R)',4000000.0,'Bowler','SRH');
INSERT INTO player(name,price,role,label) VALUES ('Ambati Rayadu (R)',22000000.0,'Batsman','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Monu Singh (R)',2000000.0,'Batsman','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Murali Vijay (R)',20000000.0,'Batsman','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Ruturaj Gaikwad (R)',2000000.0,'Batsman','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Suresh Raine (R)',110000000.0,'Batsman','CSK');
INSERT INTO player(name,price,role,label) VALUES ('MS Dhoni (R)',150000000.0,'Wicket Keeper','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Jagadeesan Narayan (R)',2000000.0,'Wicket Keeper','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Asif K M (R)',4000000.0,'All-Rounder','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Dwayne Bravo (R)',64000000.0,'All-Rounder','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Faf du Plessis (R)',16000000.0,'All-Rounder','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Karn Sharma (R)',50000000.0,'All-Rounder','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Kedar Jadhav (R)',78000000.0,'All-Rounder','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Ravindra jadeja (R)',70000000.0,'All-Rounder','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Shane Watson (R)',40000000.0,'All-Rounder','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Sam Curran',55000000.0,'All-Rounder','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Deepak Chahar (R)',8000000.0,'Bowler','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Harbhajan Singh (R)',20000000.0,'Bowler','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Imran Tahir (R)',10000000.0,'Bowler','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Lungisani Ngidi (R)',5000000.0,'Bowler','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Mitchell Santner (R)',5000000.0,'Bowler','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Shardul Thakur (R)',26000000.0,'Bowler','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Piyush Chawla',67500000.0,'Bowler','CSK');
INSERT INTO player(name,price,role,label) VALUES ('Josh Hazlewood',20000000.0,'Bowler','CSK');
INSERT INTO player(name,price,role,label) VALUES ('R. Sai Kishore',2000000.0,'Bowler','CSK');
